export default [{
    parent: document.getElementById('animation'),
    duration: 4000,
    easing: 'expo.inout'
}, {
    duration: 4000,
    easing: 'expo.inout'
}, {
    duration: 4000,
    easing: 'expo.inout'
}, {
    duration: 1000,
    easing: 'cubic.inout'
}, {
    duration: 4000,
    easing: 'expo.inout'
}, {
    duration: 4000,
    easing: 'expo.inout'
}, {
    duration: 1000,
    easing: 'cubic.inout'
}, {
    duration: 4000,
    easing: 'expo.inout'
}, {
    duration: 1000,
    easing: 'cubic.inout'
}]